# Generated by Django 5.2.15 on 2026-09-07 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_vendor_style_purchaseorder_stageleadtime_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
