# Generated by Django 5.2.15 on 2026-09-15 00:00

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_orderdetail_category_orderdetail_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='current_stage_entered_at',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='tentative_completion_date',
        ),
        migrations.DeleteModel(
            name='StageLeadTime',
        ),
        migrations.CreateModel(
            name='TaskStateTarget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_targets', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_targets', to='db.state')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Task State Target',
                'verbose_name_plural': 'Task State Targets',
                'db_table': 'task_state_targets',
                'ordering': ('state__sequence',),
            },
        ),
        migrations.AddConstraint(
            model_name='taskstatetarget',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('issue', 'state'), name='task_state_target_unique_issue_state_when_not_deleted'),
        ),
    ]
