# Generated by Django 5.2.15 on 2026-09-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0125_taskstatetarget_remove_orderdetail_stage_fields_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='vendor_promised_date',
        ),
    ]
