# Generated by Django 5.2.15 on 2026-09-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0126_remove_orderdetail_vendor_promised_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='order_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
