# Generated by Django 5.2.15 on 2026-09-23 00:00

import uuid

from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0127_orderdetail_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCapacity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('capacity', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='db.vendor')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Vendor Capacity',
                'verbose_name_plural': 'Vendor Capacities',
                'db_table': 'vendor_capacities',
                'ordering': ('year', 'month'),
            },
        ),
        migrations.AddConstraint(
            model_name='vendorcapacity',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('vendor', 'year', 'month'), name='vendor_capacity_unique_vendor_year_month_when_not_deleted'),
        ),
    ]
