# Generated by Django 5.2.15 on 2026-09-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0128_vendorcapacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='increff_supplier_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(
                condition=models.Q(('deleted_at__isnull', True), models.Q(('increff_supplier_id', ''), _negated=True)),
                fields=('workspace', 'increff_supplier_id'),
                name='vendor_unique_workspace_increff_supplier_id_when_not_deleted',
            ),
        ),
    ]
