# Generated by Django 5.2.15 on 2026-09-28 00:00

from django.db import migrations, models
from django.db.models import OuterRef, Subquery, Value
from django.db.models.functions import Coalesce


def copy_purchase_order_numbers(apps, schema_editor):
    # carry the retired PO catalog's numbers over to the new free-text field
    OrderDetail = apps.get_model("db", "OrderDetail")
    PurchaseOrder = apps.get_model("db", "PurchaseOrder")
    OrderDetail._default_manager.filter(purchase_order__isnull=False).update(
        purchase_order_number=Coalesce(
            Subquery(PurchaseOrder._default_manager.filter(pk=OuterRef("purchase_order_id")).values("po_number")[:1]),
            Value(""),
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0130_backfill_task_state_target_entered_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetail",
            name="purchase_order_number",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(copy_purchase_order_numbers, migrations.RunPython.noop),
    ]
